"""add contest_filename

Revision ID: 07e08fcd463e
Revises: 303bdf887c61
Create Date: 2019-05-18 19:17:18.287971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e08fcd463e'
down_revision = '303bdf887c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('filename', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'filename')
    # ### end Alembic commands ###
