"""some id to str

Revision ID: 213715acc1c7
Revises: 24598d5d8d9b
Create Date: 2019-04-20 11:03:15.325112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '213715acc1c7'
down_revision = '24598d5d8d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('award', 'sup_teacher',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('award', 'user_id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'award', 'user', ['sup_teacher'], ['user_id'])
    op.create_foreign_key(None, 'request', 'user', ['sup_teacher'], ['user_id'])
    op.alter_column('user', 'tel_num',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tel_num',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'award', type_='foreignkey')
    op.alter_column('award', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
    op.alter_column('award', 'sup_teacher',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
    # ### end Alembic commands ###
