"""add contest_type

Revision ID: 303bdf887c61
Revises: ae798e544b8f
Create Date: 2019-05-04 19:05:57.862131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303bdf887c61'
down_revision = 'ae798e544b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_type',
    sa.Column('contest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contest_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('contest_id')
    )
    # op.create_foreign_key(None, 'contest', 'contest_type', ['contest_type'], ['contest_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'contest', type_='foreignkey')
    op.drop_table('contest_type')
    # ### end Alembic commands ###
