"""add notice_filename

Revision ID: 54c41e678fd5
Revises: 7f184d5e5786
Create Date: 2019-04-23 16:39:52.425638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c41e678fd5'
down_revision = '7f184d5e5786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('filename1', sa.String(length=20), nullable=True))
    op.add_column('notice', sa.Column('filename2', sa.String(length=20), nullable=True))
    op.add_column('notice', sa.Column('filename3', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'filename3')
    op.drop_column('notice', 'filename2')
    op.drop_column('notice', 'filename1')
    # ### end Alembic commands ###
