"""student,study or work

Revision ID: 6392b953b1c7
Revises: 6991b0768d5a
Create Date: 2019-04-13 09:27:35.612332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6392b953b1c7'
down_revision = '6991b0768d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('college_name', sa.String(length=30), nullable=True))
    op.add_column('student', sa.Column('college_type', sa.String(length=30), nullable=True))
    op.add_column('student', sa.Column('company_name', sa.String(length=30), nullable=True))
    op.add_column('student', sa.Column('company_type', sa.String(length=30), nullable=True))
    op.add_column('student', sa.Column('job', sa.String(length=30), nullable=True))
    op.add_column('student', sa.Column('salary', sa.Integer(), nullable=True))
    op.drop_column('student', 'work_name')
    op.drop_column('student', 'work_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('work_type', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('student', sa.Column('work_name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('student', 'salary')
    op.drop_column('student', 'job')
    op.drop_column('student', 'company_type')
    op.drop_column('student', 'company_name')
    op.drop_column('student', 'college_type')
    op.drop_column('student', 'college_name')
    # ### end Alembic commands ###
