"""tel_num from study to user

Revision ID: 7005ec988c5d
Revises: 6392b953b1c7
Create Date: 2019-04-13 10:36:12.461435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7005ec988c5d'
down_revision = '6392b953b1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'tel_num')
    op.add_column('user', sa.Column('tel_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tel_num')
    op.add_column('student', sa.Column('tel_num', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
