"""add index user

Revision ID: 74d82a8a86cb
Revises: b20fc2b34e5a
Create Date: 2019-05-28 10:38:29.973692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d82a8a86cb'
down_revision = 'b20fc2b34e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.drop_index('user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id', 'user', ['user_id'], unique=True)
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    # ### end Alembic commands ###
