"""request_sup_teacher_type to int

Revision ID: a812f85b7a69
Revises: bad818ac3e20
Create Date: 2019-04-09 19:58:11.721512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a812f85b7a69'
down_revision = 'bad818ac3e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'sup_teacher',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'request', 'user', ['sup_teacher'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.alter_column('request', 'sup_teacher',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
