"""contest_type_id1

Revision ID: b20fc2b34e5a
Revises: 07e08fcd463e
Create Date: 2019-05-19 16:36:39.824555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b20fc2b34e5a'
down_revision = '07e08fcd463e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_type', sa.Column('id', sa.Integer(), autoincrement=False,  nullable=False))
    op.drop_column('contest_type', 'contest_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_type', sa.Column('contest_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('contest_type', 'id')
    # ### end Alembic commands ###
